# Generated by Django 3.0.5 on 2020-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200414_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='client',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
