# Generated by Django 3.0.5 on 2020-04-14 12:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("population", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
