# Generated by Django 3.0.5 on 2020-04-14 17:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Region", "verbose_name_plural": "Regions"},
        ),
    ]
