# Generated by Django 3.0.5 on 2020-12-12 15:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_auto_20200414_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="official_link",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
