# Generated by Django 3.0.5 on 2020-12-12 14:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_auto_20200416_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="official_link",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
