# Generated by Django 3.0.5 on 2020-12-12 15:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_hospital_official_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="official_link",
        ),
    ]
